apiVersion: v1
kind: Service
metadata:
  name: hello-demo
  labels:
    app: hello-demo
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-demo
    tier: hello-demo
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-demo
  labels:
    app: hello-demo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-demo
        tier: hello-demo
    spec:
      containers:
      - image: harikni/hello-demo:latest
        name: hello-demo
        ports:
        - containerPort: 80
          name: hello-demo
